version: "3.9"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - producer-net
      - consumer-net

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "29092:29092"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/kafka/9092"]
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - producer-net
      - consumer-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lol"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - producer-net

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - producer-net

  spark-master:
    image: spark:3.5.1
    container_name: spark-master
    entrypoint:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
    environment:
      SPARK_MASTER_HOST: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - consumer-net

  spark-worker:
    image: spark:3.5.1
    container_name: spark-worker
    user: root
    depends_on:
      - spark-master
    entrypoint:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - --cores
      - "12"
      - --memory
      - "6g"
      - spark://spark-master:7077
    volumes:
      - spark-checkpoints-players:/checkpoints/players
      - spark-checkpoints-scoreboardplayers:/checkpoints/scoreboardplayers
    networks:
      - consumer-net

  producer-players:
    image: ghcr.io/${OWNER}/${REPO}/producer:${APP_TAG}
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["players"]
    networks:
      - producer-net

  producer-scoreboard:
    image: ghcr.io/${OWNER}/${REPO}/producer:${APP_TAG}
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["scoreboard"]
    networks:
      - producer-net

  spark-consumer-players:
    image: ghcr.io/${OWNER}/${REPO}/consumer:${APP_TAG}
    user: root
    depends_on:
      spark-master:
        condition: service_started
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CONSUMER_MODE: players
    volumes:
      - spark-checkpoints-players:/checkpoints
    networks:
      - consumer-net
    restart: always

  spark-consumer-scoreboard:
    image: ghcr.io/${OWNER}/${REPO}/consumer:${APP_TAG}
    user: root
    depends_on:
      spark-master:
        condition: service_started
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CONSUMER_MODE: scoreboard
    volumes:
      - spark-checkpoints-scoreboardplayers:/checkpoints
    networks:
      - consumer-net
    restart: always

  spark-consumer-players-stats:
    image: ghcr.io/${OWNER}/${REPO}/consumer:${APP_TAG}
    user: root
    depends_on:
      spark-master:
        condition: service_started
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      AZURE_SQL_SERVER: ${AZURE_SQL_SERVER}
      AZURE_SQL_DB: ${AZURE_SQL_DB}
      AZURE_SQL_USER: ${AZURE_SQL_USER}
      AZURE_SQL_PASSWORD: ${AZURE_SQL_PASSWORD}
    command: ["/opt/spark/bin/spark-submit --master spark://spark-master:7077 --deploy-mode client --driver-memory 2g --executor-memory 2g --executor-cores 2 --conf spark.executorEnv.KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP} --conf spark.executorEnv.AZURE_SQL_SERVER=${AZURE_SQL_SERVER} --conf spark.executorEnv.AZURE_SQL_DB=${AZURE_SQL_DB} --conf spark.executorEnv.AZURE_SQL_USER=${AZURE_SQL_USER} --conf spark.executorEnv.AZURE_SQL_PASSWORD=${AZURE_SQL_PASSWORD} --class consumer.PlayersStats /opt/app/app.jar"]
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g
    volumes:
      - spark-checkpoints-players-stats:/checkpoints
    networks:
      - consumer-net
    restart: always

networks:
  producer-net:
    driver: bridge
  consumer-net:
    driver: bridge

volumes:
  postgres-data:
  spark-checkpoints-players:
  spark-checkpoints-scoreboardplayers:
  spark-checkpoints-players-stats:
  kafka-data:
